version: '3.6'

services:
  resource:
    image: "raym123/resource2:latest"
    deploy:
      replicas: 1
      update_config:
        delay: 1m
        order: start-first
    hostname: "resource2"
    ports:
      - "8301:8301"
    networks:
      - "my-overlay"
    environment:
      - "SERVER_PORT=8301"
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_CLOUD_CONFIG_URI=http://test:dfesdf@config:8081"

networks:
  my-overlay:
    driver: "overlay"
    external: true