version: '3.6'

services:
  resource:
    image: "raym123/resource2:latest"
    deploy:
      replicas: 2
      update_config:
        delay: 2m
    hostname: "resource2"
    ports:
      - "8301:8301"
    networks:
      - "my-overlay"
    environment:
      - "SERVER_PORT=8301"
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_CLOUD_CONFIG_URI=http://test:dfesdf@config:8081"
    healthcheck:
      test: curl --fail -s http://localhost:8301/resource2/actuator/health || exit 1
      interval: 30s
      start_period: 1m30s
      retries: 5

networks:
  my-overlay:
    driver: "overlay"
    external: true