version: '3'
services:
  resource:
    image: "raym123/resource2:latest"
    deploy:
      replicas: 2
    hostname: "resource2"
    ports:
      - "8301:8301"
    networks:
      - "my-overlay"
    environment:
      - "SERVER_PORT=8301"
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_CLOUD_CONFIG_URI=http://config1:8081,http://config2:8082"

networks:
  my-overlay:
    driver: "overlay"
    external: true