version: '3.6'
services:
  jwtauth:
    image: "raym123/jwtauth:latest"
    deploy:
      replicas: 1
      update_config:
        delay: 1m
        order: start-first
    hostname: "jwtauth"
    ports:
      - "8085:8085"
    networks:
      - "my-overlay"
    environment:
      - "SERVER_PORT=8085"
      - "SPRING_PROFILES_ACTIVE=dev"

networks:
  my-overlay:
    driver: "overlay"
    external: true