version: '3'
services:
  gateway:
    image: "raym123/gateway:latest"
    deploy:
      replicas: 1
    hostname: "gateway"
    ports:
      - "8080:8080"
    networks:
      - "my-overlay"
    environment:
      - "SERVER_PORT=8080"
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_CLOUD_CONFIG_URI=http://test:dfesdf@config:8081"

networks:
  my-overlay:
    driver: "overlay"
    external: true