version: '3.6'

services:
  eureka1:
    image: "raym123/eureka:latest"
    deploy:
      replicas: 1
      update_config:
        delay: 1m
        order: start-first
    hostname: "eureka1"
    ports:
      - "8761:8761"
    networks:
      - "my-overlay"
    environment:
      - "SERVER_PORT=8761"
      - "SPRING_PROFILES_ACTIVE=dev1"
      - "SPRING_CLOUD_CONFIG_URI=http://test:dfesdf@config:8081"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka2:8762/eureka/"
    healthcheck:
      test: curl --fail -s http://localhost:8761/actuator/health || exit 1
      interval: 30s
      start_period: 1m30s
      retries: 5
  eureka2:
    image: "raym123/eureka:latest"
    deploy:
      replicas: 1
      update_config:
        delay: 1m
        order: start-first
    hostname: "eureka2"
    ports:
      - "8762:8762"
    networks:
      - "my-overlay"
    environment:
      - "SERVER_PORT=8762"
      - "SPRING_PROFILES_ACTIVE=dev2"
      - "SPRING_CLOUD_CONFIG_URI=http://test:dfesdf@config:8081"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka1:8761/eureka/"
    healthcheck:
      test: curl --fail -s http://localhost:8762/actuator/health || exit 1
      interval: 30s
      start_period: 1m30s
      retries: 5

networks:
  my-overlay:
    driver: "overlay"
    external: true