version: '3'
services:
  eureka1:
    image: "raym123/eureka:latest"
    deploy:
      replicas: 1
    hostname: "eureka1"
    ports:
      - "8761:8761"
    networks:
      - "my-overlay"
    environment:
      - "SERVER_PORT=8761"
      - "SPRING_PROFILES_ACTIVE=dev1"
      - "SPRING_CLOUD_CONFIG_URI=http://config:8081"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka2:8762/eureka/"
  eureka2:
    image: "raym123/eureka:latest"
    deploy:
      replicas: 1
    hostname: "eureka2"
    ports:
      - "8762:8762"
    networks:
      - "my-overlay"
    environment:
      - "SERVER_PORT=8762"
      - "SPRING_PROFILES_ACTIVE=dev2"
      - "SPRING_CLOUD_CONFIG_URI=http://config:8081"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka1:8761/eureka/"

networks:
  my-overlay:
    driver: "overlay"
    external: true