version: '3.6'

services:
  resource:
    image: "raym123/resource:v1"
    deploy:
      replicas: 2
      update_config:
        delay: 1m
    hostname: "resource"
    ports:
      - "8300:8300"
    networks:
      - "my-overlay"
    environment:
      - "SERVER_PORT=8300"
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_CLOUD_CONFIG_URI=http://test:dfesdf@config:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8300/resource/actuator/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  my-overlay:
    driver: "overlay"
    external: true