version: '3'
services:
  resource:
    image: "raym123/resource:latest"
    deploy:
      replicas: 2
    hostname: "resource"
    ports:
      - "8300:8300"
    networks:
      - "my-overlay"
    environment:
      - "SERVER_PORT=8300"
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_CLOUD_CONFIG_URI=http://test:dfesdf@config:8081"

networks:
  my-overlay:
    driver: "overlay"
    external: true