version: '3.6'

services:
  resource:
    image: "raym123/resource:v3"
    deploy:
      replicas: 2
      update_config:
        delay: 1m
    hostname: "resource"
    ports:
      - "8300:8300"
    networks:
      - "my-overlay"
    environment:
      - "SERVER_PORT=8300"
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_CLOUD_CONFIG_URI=http://test:dfesdf@config:8081"
    healthcheck:
      test: curl --fail -s http://localhost:8300/resource/actuator/health || exit 1
      interval: 1m30s
      start_period: 1m

networks:
  my-overlay:
    driver: "overlay"
    external: true