version: '3.6'

services:
  config:
    image: "raym123/config:latest"
    deploy:
      replicas: 1
      update_config:
        delay: 2m
    hostname: "config"
    ports:
      - "8081:8081"
    networks:
      - "my-overlay"
    environment:
      - "SERVER_PORT=8081"
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_SECURITY_USER_NAME=test"
      - "SPRING_SECURITY_USER_PASSWORD=dfesdf"
      - "ENCRYPT_KEY=dfehh43d"
    healthcheck:
      test: curl --fail -s http://localhost:8081/actuator/health || exit 1
      interval: 30s
      start_period: 1m30s
      retries: 5

networks:
  my-overlay:
    driver: "overlay"
    external: true