version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    deploy:
      replicas: 1
    ports:
     - "5672:5672"
     - "15672:15672"
    networks:
      - "my-overlay"
  config:
    image: "raym123/config:latest"
    deploy:
      replicas: 2
    hostname: "config"
    ports:
      - "8081:8081"
    networks:
      - "my-overlay"
    environment:
      - "SERVER_PORT=8081"
      - "SPRING_PROFILES_ACTIVE=dev"

networks:
  my-overlay:
    driver: "overlay"
    external: true