version: '3.6'

services:
  config:
    image: "raym123/config:latest"
    deploy:
      replicas: 1
      update_config:
        delay: 1m
        order: start-first
    hostname: "config"
    ports:
      - "8081:8081"
    networks:
      - "my-overlay"
    environment:
      - "SERVER_PORT=8081"
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_SECURITY_USER_NAME=test"
      - "SPRING_SECURITY_USER_PASSWORD=dfesdf"
      - "ENCRYPT_KEY=dfehh43d"

networks:
  my-overlay:
    driver: "overlay"
    external: true